version: "3.8"
services:
  ng:
    build:
      context: .
    stdin_open: true
    tty: true
    ports:
      - 4200:4200
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules